spring.application.name=content-moderation-system

spring.jackson.default-property-inclusion = NON_NULL

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:cmsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=128MB
spring.servlet.multipart.max-request-size=128MB